export const careersMetaData = [
  {
    id: 1,
    name: "Customer Support",
    location: "Mathura, Uttar Pradesh",
    type: "Marketing",
    role: "Resolve customer queries / issues",
  },
  {
    id: 2,
    name: "Sales Representative",
    location: "Delhi, India",
    type: "Sales",
    role: "Generate leads and close sales deals",
  },
  {
    id: 3,
    name: "Software Engineer",
    location: "Bangalore, Karnataka",
    type: "Engineering",
    role: "Develop and maintain software applications",
  },
  {
    id: 4,
    name: "Graphic Designer",
    location: "Mumbai, Maharashtra",
    type: "Creative",
    role: "Design visuals for marketing materials",
  },
  {
    id: 5,
    name: "Human Resources Specialist",
    location: "Chennai, Tamil Nadu",
    type: "Human Resources",
    role: "Manage recruitment and employee relations",
  },
  {
    id: 6,
    name: "Financial Analyst",
    location: "Hyderabad, Telangana",
    type: "Finance",
    role: "Analyze financial data and provide insights",
  },
  {
    id: 7,
    name: "Content Writer",
    location: "Pune, Maharashtra",
    type: "Content",
    role: "Create engaging and informative content",
  },
  {
    id: 8,
    name: "Network Administrator",
    location: "Kolkata, West Bengal",
    type: "IT",
    role: "Maintain and troubleshoot network infrastructure",
  },
  {
    id: 9,
    name: "Marketing Manager",
    location: "Ahmedabad, Gujarat",
    type: "Marketing",
    role: "Develop and implement marketing strategies",
  },
];
